import{a as b,S as q,i as l}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const E="51939816-d2a4c418c191417f29ceae84e",B="https://pixabay.com/api/";async function u(o,t=1){const s={key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await b.get(B,{params:s})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more");let $=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:i,comments:S,downloads:v})=>`
    <li class="gallery-item">
      <a href="${a}">
        <img src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p><span>Likes</span><span>${r}</span></p>
        <p><span>Views</span><span>${i}</span></p>
        <p><span>Comments</span><span>${S}</span></p>
        <p><span>Downloads</span><span>${v}</span></p>
      </div>
    </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){m.innerHTML=""}function L(){g.classList.remove("hidden")}function w(){g.classList.add("hidden")}function C(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const f=document.querySelector(".form"),P=document.querySelector(".load-more");let c="",n=1,p=0;d();f.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),n=1,!c){l.error({title:"Error",message:"Please enter a search term!",backgroundColor:"#ff4d4f",titleColor:"#fff",messageColor:"#fff",position:"topCenter"}),f.reset();return}M(),d(),L();try{const t=await u(c,n);if(p=t.totalHits,t.hits.length===0){l.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});return}y(t.hits),p>n*15&&C()}catch{l.error({title:"Error",message:"Something went wrong!",backgroundColor:"#ff4d4f",titleColor:"#fff",messageColor:"#fff",position:"topCenter"})}finally{w(),f.reset()}});P.addEventListener("click",async()=>{n+=1,d(),L();try{const o=await u(c,n);y(o.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),n*15>=p?(d(),l.info({title:"End",message:"You've reached the end of search results.",position:"topCenter"})):C()}catch{l.error({title:"Error",message:"Something went wrong while loading more images!",position:"topCenter"})}finally{w()}});
//# sourceMappingURL=index.js.map
