import{a as q,S as v,i as c}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const S=q.create({baseURL:"https://pixabay.com/api/",params:{key:"51939816-d2a4c418c191417f29ceae84e",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function f(r,t,a=15){return(await S.get("",{params:{q:r,page:t,per_page:a}})).data}const p=document.querySelector(".gallery");let C=new v(".gallery a");function m(r){const t=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:i,comments:w,downloads:b})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <p><span>Likes</span><span>${o}</span></p>
        <p><span>Views</span><span>${i}</span></p>
        <p><span>Comments</span><span>${w}</span></p>
        <p><span>Downloads</span><span>${b}</span></p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",t),C.refresh()}function M(){p.innerHTML=""}function g(){document.querySelector(".loader").classList.remove("is-hidden")}function y(){document.querySelector(".loader").classList.add("is-hidden")}function P(){document.querySelector(".load-more").classList.remove("is-hidden")}function h(){document.querySelector(".load-more").classList.add("is-hidden")}function L(r,t,a=15){const s=Math.ceil(r/a);t<s?P():(h(),c.info({message:"We're sorry, but you've reached the end of search results."}))}function $(){const r=document.querySelector(".gallery").firstElementChild;if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const x=document.querySelector(".form"),B=document.querySelector(".load-more");let l="",n=1,u=0;const d=15;x.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),l===""){c.warning({title:"Warning",message:"Empty input field",backgroundColor:"#ff4d4f",messageColor:"#fff"});return}n=1,M(),h(),g();try{const t=await f(l,n,d);if(u=t.totalHits,t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query.Please try again!"});return}m(t.hits),L(u,n,d)}catch{c.error({message:"An error occurred while fetching images. Please try again.",backgroundColor:"#ff4d4f",messageColor:"#fff"})}finally{y()}r.target.reset()});B.addEventListener("click",async()=>{n+=1,g();try{const r=await f(l,n,d);m(r.hits),L(u,n,d),$()}catch{c.error({message:"An error occurred while fetching images. Please try again."})}finally{y()}});
//# sourceMappingURL=index.js.map
