import{a as q,S as C,i as l}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const $="51939816-d2a4c418c191417f29ceae84e",H="https://pixabay.com/api/";async function m(o,t=1,s=15){const n={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s};try{return(await q.get(H,{params:n})).data}catch(e){return console.error("Error fetching images:",e),{hits:[],totalHits:0}}}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".load-more");let M=new C(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){const t=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:c,comments:S,downloads:b})=>`
    <li class="gallery-item">
      <a href="${n}">
        <img src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p><span>Likes</span><span>${r}</span></p>
        <p><span>Views</span><span>${c}</span></p>
        <p><span>Comments</span><span>${S}</span></p>
        <p><span>Downloads</span><span>${b}</span></p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function B(){h.innerHTML=""}function w(){g.classList.remove("is-hidden")}function v(){g.classList.add("is-hidden")}function O(){y.classList.remove("is-hidden")}function E(){y.classList.add("is-hidden")}const u=document.querySelector(".form"),P=document.querySelector(".load-more");let d="",a=1,p=0;const f=15;let i=!1;u.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.currentTarget.elements["search-text"].value.trim(),!d){l.error({title:"Error",message:"Please enter a search term!",backgroundColor:"#ff4d4f",titleColor:"#fff",messageColor:"#fff",position:"topRight"}),u.reset();return}a=1,B(),E(),w(),i=!0;try{const t=await m(d,a,f);if(p=t.totalHits,t.hits.length===0){l.info({title:"No results",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}L(t.hits)}catch{l.error({title:"Error",message:"Something went wrong!",backgroundColor:"#ff4d4f",titleColor:"#fff",messageColor:"#fff",position:"topRight"})}finally{v(),i=!1,u.reset()}});P.addEventListener("click",async()=>{if(!i){a+=1,w(),i=!0;try{const o=await m(d,a,f);L(o.hits),a*f>=p&&(E(),l.info({title:"End",message:"You've reached the end of search results.",position:"topCenter"}))}catch{l.error({message:"Error fetching more images"})}finally{v(),i=!1}}});window.addEventListener("scroll",()=>{const{scrollTop:o,scrollHeight:t,clientHeight:s}=document.documentElement;o+s>=t-10&&!i&&a*f<p&&O()});
//# sourceMappingURL=index.js.map
